# Site settings
baseurl = "jmpargana.github.io"
languageCode = "en-us"
title = "jmpargana"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "jmpargana"
    description = "jmpargana official website"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "jmpargana@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "jmpargana official"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "jmpargana.jpg"
        name = "jmpargana"
        subtitle = "Musician - Programmer - Linguist"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Skillset"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "João Pargana is both artist and scientist. He studied piano at HfMDK Frankfurt followed by computer science in the Goethe-University of the same city. His broad range of interests are reflected in computer science where he has learned multiple languages, and is fascinated with topics starting from embedded hardware systems and pentesting to web and mobile development."
        right = "His technical background in music manifests itself in his approach to learn and practice any skill with lots of dedication in his private time. Besides his professional fields, João is particularly interested in linguistics, which is shown by his fluency in the english, portuguese, german, russian and spanish language, as well as his attitude towards machine learning, especially natural language processing."
        [params.about.button]
            text = "Resume"
            link = "//github.com/jmpargana/jmpargana/archive/Resume.pdf"
            icon = "download"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Franfurt am Main", "Germany"]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/jmpargana"

            [[params.footer.social.networks]]
                icon = "fa-stack-overflow"
                link=  "//stackoverflow.com/users/10599843/jmpargana"


        [params.footer.credits]
            title = "Hugo Freelance Theme"
            text = "Freelance is a free to use, open source Bootstrap theme created by [Start Bootstrap](//startbootstrap.com)."
